variable "ENV" {}
variable "COMPONENT" {}
variable "INSTANCE_TYPE" {}
variable "APP_PORT" {}
variable "WORKSTATION_IP" {}
variable "APP_VERSION" {}
variable "APP_TYPE" {}
variable "PROMETHEUS_IP" {}
variable "DESIRED_CAPACITY" {}
variable "MIN_SIZE" {}
variable "MAX_SIZE" {}